### ISSUE TITLE
Document recommended way to restart the controller and gateway

### ISSUE THREAD

**Issue by dandv** [ib-controller/ib-controller#141]
About a week ago, my IB Gateway got stuck in a state where it's no longer accepting API connections. The last lines of the log are below:

```
22:06:09:002 JTS-CCPDispatcherS736-77802: Error
twslaunch.jutils.SLogging$Warning: Cannot apply FixDailyPnL response to unknown account; reqId=PLR.105
	at twslaunch.jutils.ic.t(ic.java:439)
	at feature.pnl.g.a(g.java:172)
	at jconnection.usermsg.k.a(k.java:42)
	at jconnection.usermsg.z.a(z.java:128)
	at jconnection.ec.b(ec.java:632)
	at jconnection.ec.a(ec.java:455)
	at jconnection.cc.a(cc.java:260)
	at jconnection.cc.b(cc.java:308)
	at jconnection.cc.a(cc.java:216)
	at jconnection.cc.k(cc.java:143)
	at twslaunch.jconnection.zb.run(zb.java:133)
00:00:07:125 JTS-CCPDispatcherS736-77802: LogRotate: no change; /home/dandv/Jts/ibgateway.Sat.log vs /home/dandv/Jts/ibgateway.Sat.log
03:08:37:275 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268449000 elapsed:11000
03:08:38:276 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268450000 elapsed:12000
03:08:39:276 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268451000 elapsed:13000
03:08:40:276 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268452000 elapsed:14000
03:08:41:277 JTS-CCPPingS736-77801: Warning: sending test request at 2268453000
03:08:42:277 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268454000 elapsed:16000
03:08:43:278 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268455000 elapsed:17000
03:08:44:278 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268456000 elapsed:18000
03:08:45:278 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268457000 elapsed:19000
03:08:46:279 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268458000 elapsed:20000
03:08:47:279 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268459000 elapsed:21000
03:08:48:279 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268460000 elapsed:22000
03:08:49:280 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268461000 elapsed:23000
03:08:50:280 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268462000 elapsed:24000
03:08:51:281 JTS-CCPPingS736-77801: Warning: not received heartbeat at 2268463000 elapsed:25000
21:02:11:712 JTS-Fuse-ClosedSocket-80623: HTBP Disconnected from live peer!:cdc1.ibllc.com:4001 (SSL)
22:52:05:968 JTS-AuthDispatcherS925-91453:  NS_AUTH_START version=19 pwd=0 soft=2 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=MARKET_DATA_CONNECTION identityHashcode=1184552776
22:52:06:081 JTS-AuthDispatcherS925-91453: setting session token in AuthenticationHandler: authenticationType=MARKET_DATA_CONNECTION hashCode=1184552776 new=385803318452334739308675821834884729147632123202 old=385803318452334739308675821834884729147632123202 ctciOld=null
22:52:06:149 JTS-PostAuthenticateS925-91459: pre-logon message successfully sent
22:52:06:001 AWT-EventQueue-0: Ignore duplicate init()
22:52:06:004 AWT-EventQueue-0: Warning: hot restart not equal to quick restart
22:52:06:005 AWT-EventQueue-0: Unsubscribe MD before routing table rerequest
22:52:06:005 AWT-EventQueue-0: Prepare HMDS parties for routing table update
22:52:06:007 AWT-EventQueue-0: Reconnected! session:925
22:52:06:007 JTS-ushmdsDispatcherS927-91472:  NS_AUTH_START version=7 pwd=1 soft=0 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=1630652558
22:52:06:160 JTS-usfarmDispatcherS926-91469:  NS_AUTH_START version=7 pwd=1 soft=0 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=1003011736
22:52:06:392 JTS-ForwardRouting-HISTORICAL_DATA-91480: handleCompatibleRouting HISTORICAL_DATA compmode=true ready=false farm=ushmds
22:52:07:330 JTS-ForwardRouting-MARKET_DATA-91487: handleCompatibleRouting MARKET_DATA compmode=true ready=false farm=usfarm
22:52:07:807 JTS-usfarm.usDispatcherS928-91490:  NS_AUTH_START version=7 pwd=1 soft=0 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=2073022228
22:52:08:172 JTS-usfutureDispatcherS929-91494:  NS_AUTH_START version=7 pwd=1 soft=0 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=1898350072
00:00:07:487 JTS-CCPDispatcherS925-91463: LogRotate: no change; /home/dandv/Jts/ibgateway.Sat.log vs /home/dandv/Jts/ibgateway.Sat.log
00:00:08:057 JTS-CCPDispatcherS925-91463: Error
twslaunch.jutils.SLogging$Warning: Daily PnL: could not apply initial data to conid= 215465475 account=U327195.; data=m_positionAtMidnight=1.0;m_moneyTradedSinceMidnight=107263.48;m_realizedPnLSinceMidnight=116.44
	at twslaunch.jutils.ic.t(ic.java:439)
	at jexec.p.a(p.java:1541)
	at feature.pnl.g.a(g.java:187)
	at jconnection.usermsg.k.a(k.java:42)
	at jconnection.usermsg.z.a(z.java:128)
	at jconnection.ec.b(ec.java:632)
	at jconnection.ec.a(ec.java:455)
	at jconnection.cc.a(cc.java:260)
	at jconnection.cc.b(cc.java:308)
	at jconnection.cc.a(cc.java:216)
	at jconnection.cc.k(cc.java:143)
	at twslaunch.jconnection.zb.run(zb.java:133)
00:00:08:058 JTS-CCPDispatcherS925-91463: Error
twslaunch.jutils.SLogging$Warning: AccountTradingSummary: could not set priceAtMidnight = 5351.0 to contract=215465475 account=U327195.
	at twslaunch.jutils.ic.t(ic.java:439)
	at jexec.p.a(p.java:1556)
	at feature.pnl.g.b(g.java:222)
	at jconnection.usermsg.j.a(j.java:45)
	at jconnection.usermsg.z.a(z.java:128)
	at jconnection.ec.b(ec.java:632)
	at jconnection.ec.a(ec.java:455)
	at jconnection.cc.a(cc.java:260)
	at jconnection.cc.b(cc.java:308)
	at jconnection.cc.a(cc.java:216)
	at jconnection.cc.k(cc.java:143)
	at twslaunch.jconnection.zb.run(zb.java:133)
06:16:59:609 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359538000 elapsed:11000
06:17:00:609 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359539000 elapsed:12000
06:17:01:610 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359540000 elapsed:13000
06:17:02:610 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359541000 elapsed:14000
06:17:03:611 JTS-CCPPingS925-91462: Warning: sending test request at 2359542000
06:17:04:611 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359543000 elapsed:16000
06:17:05:612 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359544000 elapsed:17000
06:17:06:612 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359545000 elapsed:18000
06:17:07:613 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359546000 elapsed:19000
06:17:08:613 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359547000 elapsed:20000
06:17:09:613 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359548000 elapsed:21000
06:17:10:613 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359549000 elapsed:22000
06:17:11:614 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359550000 elapsed:23000
06:17:12:614 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359551000 elapsed:24000
06:17:13:615 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359552000 elapsed:25000
06:17:14:615 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359553000 elapsed:26000
06:17:15:615 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359554000 elapsed:27000
06:17:16:616 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359555000 elapsed:28000
06:17:17:616 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359556000 elapsed:29000
06:17:18:616 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359557000 elapsed:30000
06:17:18:931 JTS-DisconnectedS928-92389: HTBP Disconnected from live peer!::0
06:17:19:617 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359558000 elapsed:31000
06:17:19:804 JTS-usfarm.usDispatcherS930-92392:  NS_AUTH_START version=7 pwd=1 soft=0 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=FARM_AUTH identityHashcode=2080914858
06:17:20:617 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359559000 elapsed:32000
06:17:21:617 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359560000 elapsed:33000
06:17:22:618 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359561000 elapsed:34000
06:17:23:618 JTS-CCPPingS925-91462: Warning: not received heartbeat at 2359562000 elapsed:35000
06:17:24:621 JTS-CCPPingS925-91462: HTBP Disconnected from live peer!:cdc1.ibllc.com:4001 (SSL)
06:17:46:005 JTS-Login-92398: Error: creating socket failed: cdc1.ibllc.com:4001 (SSL) 
java.net.SocketTimeoutException: connect timed out
06:17:46:300 JTS-AuthDispatcherS932-92401:  NS_AUTH_START version=19 pwd=0 soft=2 token=0 tokenSubtype=0 initialTokenType=SOFT authenticationType=MARKET_DATA_CONNECTION identityHashcode=73817727
06:17:46:412 JTS-AuthDispatcherS932-92401: setting session token in AuthenticationHandler: authenticationType=MARKET_DATA_CONNECTION hashCode=73817727 new=385803318452334739308675821834884729147632123202 old=385803318452334739308675821834884729147632123202 ctciOld=null
06:17:46:473 JTS-PostAuthenticateS932-92406: pre-logon message successfully sent
06:17:47:004 AWT-EventQueue-0: Reconnected! session:932
06:57:46:592 JTS-Fuse-ClosedSocket-92492: HTBP Disconnected from live peer!:cdc1.ibllc.com:4001 (SSL)
08:20:14:444 JTS-AuthTimeoutMonitorThread-94115: Authentication timeout
08:21:42:572 JTS-AuthTimeoutMonitorThread-94223: Authentication timeout
08:22:36:052 JTS-AsyncNonLocked-23: Terminating async queue thread
08:22:36:052 JTS-Async-22: Terminating async queue thread
08:22:36:052 JTS-RecordNotifier-26: Terminating async queue thread
08:22:36:060 JTS-CCPListenerS1076-94325: Connection is already closed
08:22:36:060 JTS-CCPListenerS1076-94325: Terminating Listener thread
08:22:36:070 JTS-ShutdownTask-Shutdown_API-94333: Can't send message, not connected
08:22:36:072 JTS-EServerSocketNotifier-43596: Terminating async queue thread
08:22:36:072 JTS-EServerSocket-43595: [1:62:76:1:0:0:0:ERR] Socket connection for client{1} has closed. 
08:22:36:073 JTS-EServerSocket-43595: Can't send message, not connected
08:22:36:763 JTS-ExecNotifier-28: Terminating async queue thread
08:22:36:766 JTS-Order-Audit-10: Terminating async queue thread
```

I presume this log is generated by the Gateway, so there's no way to add dates? Timestamps are pretty useless in trying to debug what happened over a week ago.

Anyway, what is the recommended way to restart the Gateway and the IBController? Would be nice to document this in the [User guide](https://github.com/ib-controller/ib-controller/blob/master/userguide.md).

**UPDATE** I've just launched the controller again with `DISPLAY=:0 /opt/IBController/IBControllerGatewayStart.sh` and now the Gateway is accepting connections. Didn't have to re-launch the gateway. Any idea what might have happened?

**Comment by rlktradewright** [comment]
The first line of the gateway log contains the date.

You restart IBController the same way as you started it, just like any other program. I can't see why that would need to be documented in the User Guide.

I also don't understand what you mean in your update. You can't launch IBController without it starting the Gateway. Gateway/TWS are loaded inside the IBController process.

**Comment by dandv** [comment]
> You restart IBController the same way as you started it, just like any other program.

As in, by running `/opt/IBController/IBControllerGatewayStart.sh` as the user owning the `IBController.ini file`?

>  I can't see why that would need to be documented in the User Guide.

I'm trying to relaunch the controller and Gateway weekly and today I found that I ended up with two instances of it and the gateway. One was launched by the weekly cron job, and the other by a startup script in `etc/rc.local` that runs `sudo -i -u dan DISPLAY=:0 /opt/IBController/IBControllerGatewayStart.sh`. Just trying to see what I'm doing wrong given that I get two instances:

![image](https://cloud.githubusercontent.com/assets/33569/26767359/260027a4-4954-11e7-8a99-442ac153aa68.png)

**Comment by rlktradewright** [comment]
It seems to me that you have a fundamental misunderstanding somewhere. 

IBController is just an ordinary program. One you start it, it keeps running until:

* something causes the Gateway/TWS to shut down (since Gateway/TWS run inside IBController's process, when they end the process IBController goes with it)
* the time specified in the  `ClosedownAt` setting in IBController.ini is reached
* something kills it
* you send it a STOP command via TCP  IBController's command server  listens on TCP port 7462 by default)

So if you start IBController with a weekly cron job, and don't do one of the things above, then cron will simply start another instance. And if you run IBControllerGatewayStart.sh via a startup script, that will also create an instance. 

Thus you need to make sure IBController is not already running before invoking the start script by any method. The simplest way to do this is to use the `ClosedownAt` setting in IBController.ini, so you can for example set it to close down automatically at midnight every Friday or whatever suits you.

By the way, you seem to be using Java 7. Why? If you follow the standard setup for IBController, you'd be using the hidden version of Java 8 that is installed with TWS/Gateway (in which case you don't need a free-standing installation of Java at all unless you have other Java programs that need it). The advantage of this is that you're using the version of Java that IB used to build and test it.

**Comment by rlktradewright** [comment]
@dandv 

Have you got this sorted? If so, please close this issue.

**Comment by dandv** [comment]
Thanks for the clarifications. I've been using `ClosedownAt`. As for Java 7, not sure (if it ain't broken, why fix it), but it will be the first thing I'll check if I encounter problems in the future.

**Comment by dwlima2** [comment]
While I have vncserver starting upon boot up, I cannot get IBControllerGatewayStart.sh to start in crob. In sudo crontab -e, I have: * * * * * env DISPLAY=:1 /opt/IBController/IBControllerGatewayStart.sh
I have tried various other options, but none work. Any advice please?

**Comment by shevkoplyas** [comment]
Can you explain what those 5 stars mean in your crontab line " * * * * * " ?
Are you sure your "env" thing actually passing env into the bash script?
Do you know on behalf of which user cron will try to execute your script?
Did you try to run same script on behalf of that user manually (and it
worked)?
Do you know what is the difference in the environment for you, logged into
the interactive shell as that user vs cron running something as that user?

To get some of the answers try to put a simpler script 1st:

[image: Inline image 1]

then call it as you call it now by editing "crontab -e":
[image: Inline image 2]

Now compare "set" output for 2 cases:  from your command line when you run
interactively vs. what you get from your /tmp/wtf.set.output file:

[image: Inline image 3]

cheers,
Dmitry

**Comment by dwlima2** [comment]
I got it to work by running the same command under the user and not as root. ***** was just to run it every min for debugging. Thanks!
