### ISSUE TITLE
An error of the directory of TWS in windows 10.

### ISSUE THREAD

**Issue by norvar** [ib-controller/ib-controller#53]
Hi，
I downloaded and run ib-controller. I had the following print out. The error is the line of

08:56:24:484 IBController: TWS settings directory is C:\programs\Jts

while my configuration is

C:\IBController>set TWSDIR=C:\Jts\

Thanks

/////////////////////////////////////////////////////////////////////////////
C:\IBController>IBControllerStart.bat

C:\IBController>set TWSUSERID=xxxxx

C:\IBController>set TWSPASSWORD=xxxxx

C:\IBController>set IBCDIR=C:\IBController

C:\IBController>set IBCINI="C:\IBController\IBController.ini"

C:\IBController>set TWSDIR=C:\Jts\

C:\IBController>set TWSCP=jts.jar;total.2015b.jar

C:\IBController>set JAVAOPTS=-Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true -Xmx1024M -XX:MaxPermSize=256M

C:\IBController>pushd C:\Jts\

C:\Jts>setlocal

C:\Jts>set JAVA_TOOL_OPTIONS=

C:\Jts>C:\programs\Java\jdk1.7.0_79\bin\java.exe -cp  jts.jar;total.2015b.jar;C:\IBController\IBController.jar -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true -Xmx1024M -XX:MaxPermSize=256M ibcontroller.IBController "C:\IBController\IBController.ini" xxxxx xxxxx
System Properties
------------------------------------------------------------
swing.boldMetal = false
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = C:\programs\Java\jdk1.7.0_79\jre\bin
java.vm.version = 24.79-b02
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = ;
java.vm.name = Java HotSpot(TM) Client VM
file.encoding.pkg = sun.io
user.country = US
user.script =
sun.java.launcher = SUN_STANDARD
sun.os.patch.level =
java.vm.specification.name = Java Virtual Machine Specification
user.dir = C:\Jts
java.runtime.version = 1.7.0_79-b15
java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs = C:\programs\Java\jdk1.7.0_79\jre\lib\endorsed
os.arch = x86
java.io.tmpdir = C:\Users\xyang\AppData\Local\Temp\
line.separator =

java.vm.specification.vendor = Oracle Corporation
user.variant =
os.name = Windows 8.1
sun.java2d.noddraw = true
sun.jnu.encoding = GBK
java.library.path = C:\programs\Java\jdk1.7.0_79\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\programs\Java\jdk1.7.0_79\bin;.
java.specification.name = Java Platform API Specification
java.class.version = 51.0
sun.management.compiler = HotSpot Client Compiler
os.version = 6.3
user.home = C:\Users\xyang
user.timezone = America/New_York
java.awt.printerjob = sun.awt.windows.WPrinterJob
file.encoding = Cp1252
java.specification.version = 1.7
java.class.path = jts.jar;total.2015b.jar;C:\IBController\IBController.jar
user.name = xyang
java.vm.specification.version = 1.7
sun.java.command = ibcontroller.IBController C:\IBController\IBController.ini xxxxx xxxxx
java.home = C:\programs\Java\jdk1.7.0_79\jre
sun.arch.data.model = 32
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.windows.WToolkit
java.vm.info = mixed mode
java.version = 1.7.0_79
java.ext.dirs = C:\programs\Java\jdk1.7.0_79\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path = C:\programs\Java\jdk1.7.0_79\jre\lib\resources.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\rt.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\sunrsasign.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\jsse.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\jce.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\charsets.jar;C:\programs\Java\jdk1.7.0_79\jre\lib\jfr.jar;C:\programs\Java\jdk1.7.0_79\jre\classes
java.vendor = Oracle Corporation
file.separator = \
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = windows
sun.locale.formatasdefault = true
sun.cpu.isalist = pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
------------------------------------------------------------
08:56:24:437 IBController: ini file is C:\IBController\IBController.ini
08:56:24:437 IBController: IBControllerServer is started.
08:56:24:453 IBController: IBControllerServer listening on address: zhuji/192.168.1.117 port: 7462
08:56:24:484 IBController: TWS settings directory is C:\programs\Jts
Exception in thread "main" java.lang.NoClassDefFoundError: jclient/LoginFrame
        at ibcontroller.IBController.startTws(Unknown Source)
        at ibcontroller.IBController.startTwsOrGateway(Unknown Source)
        at ibcontroller.IBController.load(Unknown Source)
        at ibcontroller.IBController.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jclient.LoginFrame
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 4 more

**Comment by norvar** [comment]
Solved after changed the TWS directory to C:\programs\Jts and modified 

set TWSCP=jts.jar;total.2015b.jar

to

set TWSCP=jts.jar;total.2012.jar
